import yake
import spacy
nlp = spacy.load('en_core_web_sm')


STOP_WORDS=nlp.Defaults.stop_words
# print ('Before adding custom stop words=',len(STOP_WORDS))
mystopwords = ['I', 'x', '', ' ','To', 'Mr', 'Please','yet','want', 'kind regards', 'didn', 'regard', 'kind', 'Kind','ve','cassie', 'thanks', 'tell','take','Kind regards' 'will', 'xA', 'have', 'Dear', 'please', 'hello', 'Hello', 'confirm','to', 'dear', 'i', 'XA', 'Xa', 'i', 'From', 'hi', 'Hi','from', 'sincerely', 'Thank', 'regarding', 'Subject', 'subject', 'date', 'Date', 'Thank', 'thank', 'yours', 'Yours', 'told', 'dealing']
for i in mystopwords :
    STOP_WORDS.add(i)
STOP_WORDS.add('message')
STOP_WORDS.add('thanks')
STOP_WORDS.add('dear')
STOP_WORDS.add('thank')
STOP_WORDS.add('sincerely')
STOP_WORDS.add('fidelity')
STOP_WORDS.add('customer')
STOP_WORDS.add('relations')
STOP_WORDS.add('gmail')
STOP_WORDS.add('hotmail')
STOP_WORDS.add('i')
STOP_WORDS.add('xa')
STOP_WORDS.add('wishes')
STOP_WORDS.add('regards')
STOP_WORDS.add('like')
STOP_WORDS.add('hi')
STOP_WORDS.add('xa')
STOP_WORDS.add('morning')
STOP_WORDS.add('good')
STOP_WORDS.add('th')
STOP_WORDS.add('x')
STOP_WORDS.add('hello')
STOP_WORDS.add('message')
STOP_WORDS.add('thanks')
STOP_WORDS.add('dear')
STOP_WORDS.add('thank')
STOP_WORDS.add('sincerely')
STOP_WORDS.add('fidelity')
STOP_WORDS.add('customer')
STOP_WORDS.add('relations')
STOP_WORDS.add('gmail')
STOP_WORDS.add('hotmail')
STOP_WORDS.add('wishes')
STOP_WORDS.add('regards')
STOP_WORDS.add('like')
STOP_WORDS.add('hi')
STOP_WORDS.add('xa')
STOP_WORDS.add('morning')
STOP_WORDS.add('good')
STOP_WORDS.add('th')
STOP_WORDS.add('x')
#STOP_WORDS.add('account')
#STOP_WORDS.add('accounts')
#STOP_WORDS.add('cash')
STOP_WORDS.add('hello')
STOP_WORDS.add('kind')
STOP_WORDS.add('best')
STOP_WORDS.add('gilford')
STOP_WORDS.add('s')
STOP_WORDS.add('let')
STOP_WORDS.add('asap')
STOP_WORDS.add('getting')
STOP_WORDS.add('way')
STOP_WORDS.add('use')
STOP_WORDS.add('dec')
STOP_WORDS.add('day')
STOP_WORDS.add('don')
STOP_WORDS.add('wanted')
STOP_WORDS.add('way')
STOP_WORDS.add('jan')
STOP_WORDS.add('mr')
STOP_WORDS.add('tell')
STOP_WORDS.add('acc')
STOP_WORDS.add('rathbone')
STOP_WORDS.add('acc')
STOP_WORDS.add('set')
STOP_WORDS.add('james')
#STOP_WORDS.add('fund')
STOP_WORDS.add('fidelity')
def newKeys(text):
    kw_extractor = yake.KeywordExtractor()
    language = "en"
    max_ngram_size = 3
    deduplication_threshold = 0.9
    numOfKeywords = 25
    custom_kw_extractor = yake.KeywordExtractor(lan=language, n=max_ngram_size, dedupLim=deduplication_threshold, top=numOfKeywords, features=None,stopwords=STOP_WORDS)
    keywords = custom_kw_extractor.extract_keywords(text.lower())
    keys=[]
    for kw in keywords:
        keys.append(kw[0].upper())
    return keys
